<a href="https://colab.research.google.com/github/pierobadano/Desafio-TelecomX-P1/blob/main/Desafio_Telecom_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio Telecom X

En el siguiente notebook iré realizando mi codigo resolviendo el "Desafio Telecom X", aplicando todos los conocimientos aprendidos durante mi formacion como analista de datos hasta el momento

# Contexto

He sido contratado como asistente de análisis de datos en Telecom X y formare parte del proyecto "Churn de Clientes". La empresa enfrenta una alta tasa de cancelaciones y necesita comprender los factores que llevan a la pérdida de clientes.

Mi desafío será recopilar, procesar y analizar los datos, utilizando Python y sus principales bibliotecas para extraer información valiosa. A partir de tu análisis, el equipo de Data Science podrá avanzar en modelos predictivos y desarrollar estrategias para reducir la evasión.

```
Diccionario de datos
customerID: número de identificación único de cada cliente
Churn: si el cliente dejó o no la empresa
gender: género (masculino y femenino)
SeniorCitizen: información sobre si un cliente tiene o no una edad igual o mayor a 65 años
Partner: si el cliente tiene o no una pareja
Dependents: si el cliente tiene o no dependientes
tenure: meses de contrato del cliente
PhoneService: suscripción al servicio telefónico
MultipleLines: suscripción a más de una línea telefónica
InternetService: suscripción a un proveedor de internet
OnlineSecurity: suscripción adicional de seguridad en línea
OnlineBackup: suscripción adicional de respaldo en línea
DeviceProtection: suscripción adicional de protección del dispositivo
TechSupport: suscripción adicional de soporte técnico, menor tiempo de espera
StreamingTV: suscripción de televisión por cable
StreamingMovies: suscripción de streaming de películas
Contract: tipo de contrato
PaperlessBilling: si el cliente prefiere recibir la factura en línea
PaymentMethod: forma de pago
Charges.Monthly: total de todos los servicios del cliente por mes
Charges.Total: total gastado por el cliente

```




# Desarrollo

In [2]:
import pandas as pd
import numpy as np


In [3]:
url="https://raw.githubusercontent.com/alura-cursos/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json"
datos_crudos=pd.read_json(url)
df_clientes= pd.json_normalize(datos_crudos["customer"])

In [4]:
df_clientes= pd.json_normalize(datos_crudos["customer"])
df_telefono= pd.json_normalize(datos_crudos["phone"])
df_internet= pd.json_normalize(datos_crudos["internet"])
df_account= pd.json_normalize(datos_crudos["account"])


In [5]:
datos= pd.concat([datos_crudos[["customerID","Churn"]],df_clientes,df_telefono,df_internet,df_account], axis=1)

In [6]:
datos.sample(10)

customerID Churn  gender  SeniorCitizen Partner Dependents  tenure  \
4846  6630-UJZMY    No  Female              1     Yes         No       4   
422   0607-MVMGC    No    Male              0     Yes        Yes      45   
4132  5663-QBGIS    No    Male              1     Yes         No      72   
4572  6261-RCVNS   Yes  Female              0      No         No      42   
790   1116-FRYVH    No  Female              0     Yes        Yes      48   
343   0495-ZBNGW   Yes    Male              1     Yes         No       5   
1365  1972-XMUWV    No  Female              0     Yes         No      65   
2430  3396-DKDEL    No  Female              0     Yes        Yes      70   
5143  7018-WBJNK    No    Male              0      No        Yes      13   
3176  4433-JCGCG   Yes    Male              1     Yes         No      46   

     PhoneService     MultipleLines InternetService  ... OnlineBackup  \
4846          Yes               Yes     Fiber optic  ...           No   
422           Yes               Yes             DSL  ...          Yes   
4132          Yes               Yes     Fiber optic  ...          Yes   
4572          Yes                No             DSL  ...          Yes   
790            No  No phone service             DSL  ...          Yes   
343           Yes               Yes     Fiber optic  ...           No   
1365          Yes                No             DSL  ...           No   
2430          Yes               Yes     Fiber optic  ...          Yes   
5143          Yes                No     Fiber optic  ...           No   
3176          Yes               Yes     Fiber optic  ...           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
4846               No          No         Yes              No  Month-to-month   
422               Yes          No         Yes             Yes        One year   
4132               No          No         Yes             Yes        Two year   
4572              Yes         Yes          No             Yes        One year   
790                No         Yes          No              No        Two year   
343               Yes          No          No              No  Month-to-month   
1365               No         Yes         Yes              No        Two year   
2430              Yes         Yes         Yes             Yes        Two year   
5143               No          No         Yes              No  Month-to-month   
3176              Yes          No         Yes             Yes  Month-to-month   

     PaperlessBilling              PaymentMethod Charges.Monthly  \
4846              Yes           Electronic check           83.25   
422                No    Credit card (automatic)           78.75   
4132               No  Bank transfer (automatic)           98.35   
4572               No    Credit card (automatic)           73.90   
790                No               Mailed check           39.40   
343               Yes  Bank transfer (automatic)           79.90   
1365              Yes    Credit card (automatic)           59.80   
2430              Yes    Credit card (automatic)          115.15   
5143              Yes    Credit card (automatic)           78.30   
3176              Yes           Electronic check          101.00   

      Charges.Total  
4846         308.05  
422         3600.65  
4132         6929.4  
4572        3160.55  
790         1978.65  
343          343.95  
1365         3808.2  
2430           8250  
5143        1033.95  
3176        4680.05  

[10 rows x 21 columns]

In [7]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7267 non-null   object 
 1   Churn             7267 non-null   object 
 2   gender            7267 non-null   object 
 3   SeniorCitizen     7267 non-null   int64  
 4   Partner           7267 non-null   object 
 5   Dependents        7267 non-null   object 
 6   tenure            7267 non-null   int64  
 7   PhoneService      7267 non-null   object 
 8   MultipleLines     7267 non-null   object 
 9   InternetService   7267 non-null   object 
 10  OnlineSecurity    7267 non-null   object 
 11  OnlineBackup      7267 non-null   object 
 12  DeviceProtection  7267 non-null   object 
 13  TechSupport       7267 non-null   object 
 14  StreamingTV       7267 non-null   object 
 15  StreamingMovies   7267 non-null   object 
 16  Contract          7267 non-null   object 


In [46]:
columnas=datos.columns

Index(['customerid', 'churn', 'gender', 'seniorcitizen', 'partner',
       'dependents', 'tenure', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod', 'chargesmonthly', 'chargestotal',
       'cuentasdiarias'],
      dtype='object')

In [8]:
datos["customerID"].duplicated().sum()

np.int64(0)

In [9]:
for col in datos.columns:
  print(col)
  print(datos[col].unique())

customerID
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Churn
['No' 'Yes' '']
gender
['Female' 'Male']
SeniorCitizen
[0 1]
Partner
['Yes' 'No']
Dependents
['Yes' 'No']
tenure
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
PhoneService
['Yes' 'No']
MultipleLines
['No' 'Yes' 'No phone service']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes' 'No internet service']
OnlineBackup
['Yes' 'No' 'No internet service']
DeviceProtection
['No' 'Yes' 'No internet service']
TechSupport
['Yes' 'No' 'No internet service']
StreamingTV
['Yes' 'No' 'No internet service']
StreamingMovies
['No' 'Yes' 'No internet service']
Contract
['One year' 'Month-to-month' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Mailed check' 'Electronic check' 'Credit card (automati

In [10]:
datos[["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]]=datos[["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]].replace("No internet service","No")

In [11]:
datos["MultipleLines"]=datos["MultipleLines"].replace("No phone service","No")

In [12]:
datos[["Charges.Monthly","Charges.Total"]]

Charges.Monthly Charges.Total
0               65.60         593.3
1               59.90         542.4
2               73.90        280.85
3               98.00       1237.85
4               83.90         267.4
...               ...           ...
7262            55.15         742.9
7263            85.10        1873.7
7264            50.30         92.75
7265            67.85       4627.65
7266            59.00        3707.6

[7267 rows x 2 columns]

In [13]:
datos.columns=datos.columns.str.lower()

In [14]:
datos.columns=datos.columns.str.replace(".","")


In [15]:
datos["chargestotal"]=datos["chargestotal"].replace(",",".")

In [16]:
datos["chargestotal"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7267 entries, 0 to 7266
Series name: chargestotal
Non-Null Count  Dtype 
--------------  ----- 
7267 non-null   object
dtypes: object(1)
memory usage: 56.9+ KB


In [17]:
datos["chargestotal"] = datos["chargestotal"].apply(lambda x: x.replace("$","").replace(",","").strip())


https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html#pandas.to_numeric

In [18]:
datos["chargestotal"]=pd.to_numeric(datos["chargestotal"], errors="coerce") #convierto los valores vacios de haber a nan

In [19]:
datos["chargestotal"].dtype

dtype('float64')

In [20]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerid        7267 non-null   object 
 1   churn             7267 non-null   object 
 2   gender            7267 non-null   object 
 3   seniorcitizen     7267 non-null   int64  
 4   partner           7267 non-null   object 
 5   dependents        7267 non-null   object 
 6   tenure            7267 non-null   int64  
 7   phoneservice      7267 non-null   object 
 8   multiplelines     7267 non-null   object 
 9   internetservice   7267 non-null   object 
 10  onlinesecurity    7267 non-null   object 
 11  onlinebackup      7267 non-null   object 
 12  deviceprotection  7267 non-null   object 
 13  techsupport       7267 non-null   object 
 14  streamingtv       7267 non-null   object 
 15  streamingmovies   7267 non-null   object 
 16  contract          7267 non-null   object 


In [21]:
datos

customerid churn  gender  seniorcitizen partner dependents  tenure  \
0     0002-ORFBO    No  Female              0     Yes        Yes       9   
1     0003-MKNFE    No    Male              0      No         No       9   
2     0004-TLHLJ   Yes    Male              0      No         No       4   
3     0011-IGKFF   Yes    Male              1     Yes         No      13   
4     0013-EXCHZ   Yes  Female              1     Yes         No       3   
...          ...   ...     ...            ...     ...        ...     ...   
7262  9987-LUTYD    No  Female              0      No         No      13   
7263  9992-RRAMN   Yes    Male              0     Yes         No      22   
7264  9992-UJOEL    No    Male              0      No         No       2   
7265  9993-LHIEB    No    Male              0     Yes        Yes      67   
7266  9995-HOTOH    No    Male              0     Yes        Yes      63   

     phoneservice multiplelines internetservice  ... onlinebackup  \
0             Yes            No             DSL  ...          Yes   
1             Yes           Yes             DSL  ...           No   
2             Yes            No     Fiber optic  ...           No   
3             Yes            No     Fiber optic  ...          Yes   
4             Yes            No     Fiber optic  ...           No   
...           ...           ...             ...  ...          ...   
7262          Yes            No             DSL  ...           No   
7263          Yes           Yes     Fiber optic  ...           No   
7264          Yes            No             DSL  ...          Yes   
7265          Yes            No             DSL  ...           No   
7266           No            No             DSL  ...          Yes   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
0                  No         Yes         Yes              No        One year   
1                  No          No          No             Yes  Month-to-month   
2                 Yes          No          No              No  Month-to-month   
3                 Yes          No         Yes             Yes  Month-to-month   
4                  No         Yes         Yes              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7262               No         Yes          No              No        One year   
7263               No          No          No             Yes  Month-to-month   
7264               No          No          No              No  Month-to-month   
7265              Yes         Yes          No             Yes        Two year   
7266              Yes          No         Yes             Yes        Two year   

     paperlessbilling     paymentmethod chargesmonthly  chargestotal  
0                 Yes      Mailed check          65.60        593.30  
1                  No      Mailed check          59.90        542.40  
2                 Yes  Electronic check          73.90        280.85  
3                 Yes  Electronic check          98.00       1237.85  
4                 Yes      Mailed check          83.90        267.40  
...               ...               ...            ...           ...  
7262               No      Mailed check          55.15        742.90  
7263              Yes  Electronic check          85.10       1873.70  
7264              Yes      Mailed check          50.30         92.75  
7265               No      Mailed check          67.85       4627.65  
7266               No  Electronic check          59.00       3707.60  

[7267 rows x 21 columns]

In [22]:
datos["cuentasdiarias"]= (datos["chargesmonthly"]/30).round(4)

In [23]:
datos = datos.replace({"Yes":1,"No":0})
      #pandas me recomienda que utilice .infer_objects para adecuar al mejor tipo de dato automaticamente
datos = datos.infer_objects()

/tmp/ipython-input-184115587.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  datos = datos.replace({"Yes":1,"No":0})


In [24]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerid        7267 non-null   object 
 1   churn             7267 non-null   object 
 2   gender            7267 non-null   object 
 3   seniorcitizen     7267 non-null   int64  
 4   partner           7267 non-null   int64  
 5   dependents        7267 non-null   int64  
 6   tenure            7267 non-null   int64  
 7   phoneservice      7267 non-null   int64  
 8   multiplelines     7267 non-null   int64  
 9   internetservice   7267 non-null   object 
 10  onlinesecurity    7267 non-null   int64  
 11  onlinebackup      7267 non-null   int64  
 12  deviceprotection  7267 non-null   int64  
 13  techsupport       7267 non-null   int64  
 14  streamingtv       7267 non-null   int64  
 15  streamingmovies   7267 non-null   int64  
 16  contract          7267 non-null   object 


## Analisis Descriptivo

In [26]:
datos[["chargesmonthly","chargestotal","cuentasdiarias"]].describe() #analisis descriptivo media mediana y desviacion estandar

chargesmonthly  chargestotal  cuentasdiarias
count     7267.000000   7256.000000     7267.000000
mean        64.720098   2280.634213        2.157337
std         30.129572   2268.632997        1.004319
min         18.250000     18.800000        0.608300
25%         35.425000    400.225000        1.180850
50%         70.300000   1391.000000        2.343300
75%         89.875000   3785.300000        2.995850
max        118.750000   8684.800000        3.958300

In [31]:
datos["chargestotal"].isnull().sum()

np.int64(11)

In [32]:
datos[datos['chargestotal'].isna()] #habian valores nulos no detectados, puesto que las celdas estaban ocupadas, con un espacio, por lo que al momento de convetirlas a float con dtype, ocurria error
                                    # al cambiar el dtype con is numeric, convertimos estas celdas en NaN, lo que al analizar los parametros estadisticos, vemos una diferencia en el conteo

customerid churn  gender  seniorcitizen  partner  dependents  tenure  \
975   1371-DWPAZ     0  Female              0        1           1       0   
1775  2520-SGTTA     0  Female              0        1           1       0   
1955  2775-SEFEE     0    Male              0        0           1       0   
2075  2923-ARZLG     0    Male              0        1           1       0   
2232  3115-CZMZD     0    Male              0        0           1       0   
2308  3213-VVOLG     0    Male              0        1           1       0   
2930  4075-WKNIU     0  Female              0        1           1       0   
3134  4367-NUYAO     0    Male              0        1           1       0   
3203  4472-LVYGI     0  Female              0        1           1       0   
4169  5709-LVOEQ     0  Female              0        1           1       0   
5599  7644-OMVMY     0    Male              0        1           1       0   

      phoneservice  multiplelines internetservice  ...  deviceprotection  \
975              0              0             DSL  ...                 1   
1775             1              0               0  ...                 0   
1955             1              1             DSL  ...                 0   
2075             1              0               0  ...                 0   
2232             1              0               0  ...                 0   
2308             1              1               0  ...                 0   
2930             1              1             DSL  ...                 1   
3134             1              1               0  ...                 0   
3203             0              0             DSL  ...                 1   
4169             1              0             DSL  ...                 1   
5599             1              0               0  ...                 0   

      techsupport  streamingtv  streamingmovies  contract  paperlessbilling  \
975             1            1                0  Two year                 0   
1775            0            0                0  Two year                 0   
1955            1            0                0  Two year                 1   
2075            0            0                0  One year                 1   
2232            0            0                0  Two year                 0   
2308            0            0                0  Two year                 0   
2930            1            1                0  Two year                 0   
3134            0            0                0  Two year                 0   
3203            1            1                0  Two year                 1   
4169            0            1                1  Two year                 0   
5599            0            0                0  Two year                 0   

                  paymentmethod  chargesmonthly chargestotal  cuentasdiarias  
975     Credit card (automatic)           56.05          NaN          1.8683  
1775               Mailed check           20.00          NaN          0.6667  
1955  Bank transfer (automatic)           61.90          NaN          2.0633  
2075               Mailed check           19.70          NaN          0.6567  
2232               Mailed check           20.25          NaN          0.6750  
2308               Mailed check           25.35          NaN          0.8450  
2930               Mailed check           73.35          NaN          2.4450  
3134               Mailed check           25.75          NaN          0.8583  
3203  Bank transfer (automatic)           52.55          NaN          1.7517  
4169               Mailed check           80.85          NaN          2.6950  
5599               Mailed check           19.85          NaN          0.6617  

[11 rows x 22 columns]

In [39]:
datos[datos['tenure']==0] #los datos nulos corresponden a clientes que estan hace poco tiempo en la empresa (tenure 0),
                          #esto tiene sentido porque no tienen un cargo total aplicado, por lo que siguen siendo registros valiosos, la funcion describe ignora los valores Nan, no afectan a los calculos

customerid churn  gender  seniorcitizen  partner  dependents  tenure  \
975   1371-DWPAZ     0  Female              0        1           1       0   
1775  2520-SGTTA     0  Female              0        1           1       0   
1955  2775-SEFEE     0    Male              0        0           1       0   
2075  2923-ARZLG     0    Male              0        1           1       0   
2232  3115-CZMZD     0    Male              0        0           1       0   
2308  3213-VVOLG     0    Male              0        1           1       0   
2930  4075-WKNIU     0  Female              0        1           1       0   
3134  4367-NUYAO     0    Male              0        1           1       0   
3203  4472-LVYGI     0  Female              0        1           1       0   
4169  5709-LVOEQ     0  Female              0        1           1       0   
5599  7644-OMVMY     0    Male              0        1           1       0   

      phoneservice  multiplelines internetservice  ...  deviceprotection  \
975              0              0             DSL  ...                 1   
1775             1              0               0  ...                 0   
1955             1              1             DSL  ...                 0   
2075             1              0               0  ...                 0   
2232             1              0               0  ...                 0   
2308             1              1               0  ...                 0   
2930             1              1             DSL  ...                 1   
3134             1              1               0  ...                 0   
3203             0              0             DSL  ...                 1   
4169             1              0             DSL  ...                 1   
5599             1              0               0  ...                 0   

      techsupport  streamingtv  streamingmovies  contract  paperlessbilling  \
975             1            1                0  Two year                 0   
1775            0            0                0  Two year                 0   
1955            1            0                0  Two year                 1   
2075            0            0                0  One year                 1   
2232            0            0                0  Two year                 0   
2308            0            0                0  Two year                 0   
2930            1            1                0  Two year                 0   
3134            0            0                0  Two year                 0   
3203            1            1                0  Two year                 1   
4169            0            1                1  Two year                 0   
5599            0            0                0  Two year                 0   

                  paymentmethod  chargesmonthly chargestotal  cuentasdiarias  
975     Credit card (automatic)           56.05          NaN          1.8683  
1775               Mailed check           20.00          NaN          0.6667  
1955  Bank transfer (automatic)           61.90          NaN          2.0633  
2075               Mailed check           19.70          NaN          0.6567  
2232               Mailed check           20.25          NaN          0.6750  
2308               Mailed check           25.35          NaN          0.8450  
2930               Mailed check           73.35          NaN          2.4450  
3134               Mailed check           25.75          NaN          0.8583  
3203  Bank transfer (automatic)           52.55          NaN          1.7517  
4169               Mailed check           80.85          NaN          2.6950  
5599               Mailed check           19.85          NaN          0.6617  

[11 rows x 22 columns]

In [40]:
datos[datos['tenure'] > 0][['chargestotal'].describe()

count    7256.000000
mean     2280.634213
std      2268.632997
min        18.800000
25%       400.225000
50%      1391.000000
75%      3785.300000
max      8684.800000
Name: chargestotal, dtype: float64

In [48]:
datos[columnas].describe().round(4)

seniorcitizen    partner  dependents     tenure  phoneservice  \
count      7267.0000  7267.0000   7267.0000  7267.0000     7267.0000   
mean          0.1627     0.4841      0.3001    32.3465        0.9027   
std           0.3691     0.4998      0.4583    24.5718        0.2964   
min           0.0000     0.0000      0.0000     0.0000        0.0000   
25%           0.0000     0.0000      0.0000     9.0000        1.0000   
50%           0.0000     0.0000      0.0000    29.0000        1.0000   
75%           0.0000     1.0000      1.0000    55.0000        1.0000   
max           1.0000     1.0000      1.0000    72.0000        1.0000   

       multiplelines  onlinesecurity  onlinebackup  deviceprotection  \
count      7267.0000       7267.0000     7267.0000         7267.0000   
mean          0.4218          0.2860        0.3446            0.3428   
std           0.4939          0.4519        0.4753            0.4747   
min           0.0000          0.0000        0.0000            0.0000   
25%           0.0000          0.0000        0.0000            0.0000   
50%           0.0000          0.0000        0.0000            0.0000   
75%           1.0000          1.0000        1.0000            1.0000   
max           1.0000          1.0000        1.0000            1.0000   

       techsupport  streamingtv  streamingmovies  paperlessbilling  \
count    7267.0000    7267.0000        7267.0000         7267.0000   
mean        0.2895       0.3839           0.3875            0.5932   
std         0.4536       0.4864           0.4872            0.4913   
min         0.0000       0.0000           0.0000            0.0000   
25%         0.0000       0.0000           0.0000            0.0000   
50%         0.0000       0.0000           0.0000            1.0000   
75%         1.0000       1.0000           1.0000            1.0000   
max         1.0000       1.0000           1.0000            1.0000   

       chargesmonthly  chargestotal  cuentasdiarias  
count       7267.0000     7256.0000       7267.0000  
mean          64.7201     2280.6342          2.1573  
std           30.1296     2268.6330          1.0043  
min           18.2500       18.8000          0.6083  
25%           35.4250      400.2250          1.1808  
50%           70.3000     1391.0000          2.3433  
75%           89.8750     3785.3000          2.9958  
max          118.7500     8684.8000          3.9583

```
En promedio, nuestros clientes tienen 32.34 meses de antigüedad.
El 48.41% de los clientes está en pareja, y el 30% tiene dependientes (sobre el total de clientes).
Respecto a servicios adicionales contratados:
El 90.27% del total cuenta con servicio telefónico, lo que lo convierte en el servicio más común.
El 42.18% tiene más de una línea telefónica.
El 28.6% contrató seguridad en línea,
El 34.46% contrató respaldo de información en línea,
El 28.95% contrató servicio de soporte técnico,
El 34.28% contrató protección del dispositivo.
Solo el 16.27% son clientes mayores de 65 años (senior citizen).
El cargo mensual promedio es $64.72, mientras que la mediana es $70.3, lo que indica que la mitad de los clientes
paga menos y la otra mitad más que ese valor.
El cargo total promedio por cliente es $2,280.63, con una mediana de $1,391.
El gasto diario promedio es $2.16, y la mediana es $2.34.
Los valores de desviación estándar son altos en relación con sus medias,
 lo que indica una amplia dispersión en los datos, reflejando la diversidad del comportamiento de los clientes.
```


In [48]:
Diccionario de datos
customerID: número de identificación único de cada cliente
Churn: si el cliente dejó o no la empresa
gender: género (masculino y femenino)
SeniorCitizen: información sobre si un cliente tiene o no una edad igual o mayor a 65 años
Partner: si el cliente tiene o no una pareja
Dependents: si el cliente tiene o no dependientes
tenure: meses de contrato del cliente
PhoneService: suscripción al servicio telefónico
MultipleLines: suscripción a más de una línea telefónica
InternetService: suscripción a un proveedor de internet
OnlineSecurity: suscripción adicional de seguridad en línea
OnlineBackup: suscripción adicional de respaldo en línea
DeviceProtection: suscripción adicional de protección del dispositivo
TechSupport: suscripción adicional de soporte técnico, menor tiempo de espera
StreamingTV: suscripción de televisión por cable
StreamingMovies: suscripción de streaming de películas
Contract: tipo de contrato
PaperlessBilling: si el cliente prefiere recibir la factura en línea
PaymentMethod: forma de pago
Charges.Monthly: total de todos los servicios del cliente por mes
Charges.Total: total gastado por el cliente